// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lldp_neighbor.proto

package cisco_ios_xr_ethernet_lldp_oper_lldp_nodes_node_neighbors_details_detail

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LldpNeighborEntry_KEYS struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	InterfaceName        string   `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LldpNeighborEntry_KEYS) Reset()         { *m = LldpNeighborEntry_KEYS{} }
func (m *LldpNeighborEntry_KEYS) String() string { return proto.CompactTextString(m) }
func (*LldpNeighborEntry_KEYS) ProtoMessage()    {}
func (*LldpNeighborEntry_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{0}
}
func (m *LldpNeighborEntry_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpNeighborEntry_KEYS.Unmarshal(m, b)
}
func (m *LldpNeighborEntry_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpNeighborEntry_KEYS.Marshal(b, m, deterministic)
}
func (dst *LldpNeighborEntry_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpNeighborEntry_KEYS.Merge(dst, src)
}
func (m *LldpNeighborEntry_KEYS) XXX_Size() int {
	return xxx_messageInfo_LldpNeighborEntry_KEYS.Size(m)
}
func (m *LldpNeighborEntry_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpNeighborEntry_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_LldpNeighborEntry_KEYS proto.InternalMessageInfo

func (m *LldpNeighborEntry_KEYS) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *LldpNeighborEntry_KEYS) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *LldpNeighborEntry_KEYS) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type LldpL3Addr struct {
	AddressType          string   `protobuf:"bytes,1,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	Ipv4Address          string   `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address          string   `protobuf:"bytes,3,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LldpL3Addr) Reset()         { *m = LldpL3Addr{} }
func (m *LldpL3Addr) String() string { return proto.CompactTextString(m) }
func (*LldpL3Addr) ProtoMessage()    {}
func (*LldpL3Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{1}
}
func (m *LldpL3Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpL3Addr.Unmarshal(m, b)
}
func (m *LldpL3Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpL3Addr.Marshal(b, m, deterministic)
}
func (dst *LldpL3Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpL3Addr.Merge(dst, src)
}
func (m *LldpL3Addr) XXX_Size() int {
	return xxx_messageInfo_LldpL3Addr.Size(m)
}
func (m *LldpL3Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpL3Addr.DiscardUnknown(m)
}

var xxx_messageInfo_LldpL3Addr proto.InternalMessageInfo

func (m *LldpL3Addr) GetAddressType() string {
	if m != nil {
		return m.AddressType
	}
	return ""
}

func (m *LldpL3Addr) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *LldpL3Addr) GetIpv6Address() string {
	if m != nil {
		return m.Ipv6Address
	}
	return ""
}

type LldpAddrEntryItem struct {
	Address              *LldpL3Addr `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	MaSubtype            uint32      `protobuf:"varint,2,opt,name=ma_subtype,json=maSubtype,proto3" json:"ma_subtype,omitempty"`
	IfNum                uint32      `protobuf:"varint,3,opt,name=if_num,json=ifNum,proto3" json:"if_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LldpAddrEntryItem) Reset()         { *m = LldpAddrEntryItem{} }
func (m *LldpAddrEntryItem) String() string { return proto.CompactTextString(m) }
func (*LldpAddrEntryItem) ProtoMessage()    {}
func (*LldpAddrEntryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{2}
}
func (m *LldpAddrEntryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpAddrEntryItem.Unmarshal(m, b)
}
func (m *LldpAddrEntryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpAddrEntryItem.Marshal(b, m, deterministic)
}
func (dst *LldpAddrEntryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpAddrEntryItem.Merge(dst, src)
}
func (m *LldpAddrEntryItem) XXX_Size() int {
	return xxx_messageInfo_LldpAddrEntryItem.Size(m)
}
func (m *LldpAddrEntryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpAddrEntryItem.DiscardUnknown(m)
}

var xxx_messageInfo_LldpAddrEntryItem proto.InternalMessageInfo

func (m *LldpAddrEntryItem) GetAddress() *LldpL3Addr {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LldpAddrEntryItem) GetMaSubtype() uint32 {
	if m != nil {
		return m.MaSubtype
	}
	return 0
}

func (m *LldpAddrEntryItem) GetIfNum() uint32 {
	if m != nil {
		return m.IfNum
	}
	return 0
}

type LldpAddrEntryEntry struct {
	LldpAddrEntry        []*LldpAddrEntryItem `protobuf:"bytes,1,rep,name=lldp_addr_entry,json=lldpAddrEntry,proto3" json:"lldp_addr_entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LldpAddrEntryEntry) Reset()         { *m = LldpAddrEntryEntry{} }
func (m *LldpAddrEntryEntry) String() string { return proto.CompactTextString(m) }
func (*LldpAddrEntryEntry) ProtoMessage()    {}
func (*LldpAddrEntryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{3}
}
func (m *LldpAddrEntryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpAddrEntryEntry.Unmarshal(m, b)
}
func (m *LldpAddrEntryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpAddrEntryEntry.Marshal(b, m, deterministic)
}
func (dst *LldpAddrEntryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpAddrEntryEntry.Merge(dst, src)
}
func (m *LldpAddrEntryEntry) XXX_Size() int {
	return xxx_messageInfo_LldpAddrEntryEntry.Size(m)
}
func (m *LldpAddrEntryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpAddrEntryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LldpAddrEntryEntry proto.InternalMessageInfo

func (m *LldpAddrEntryEntry) GetLldpAddrEntry() []*LldpAddrEntryItem {
	if m != nil {
		return m.LldpAddrEntry
	}
	return nil
}

type LldpNeighborDetail struct {
	PeerMacAddress            string              `protobuf:"bytes,1,opt,name=peer_mac_address,json=peerMacAddress,proto3" json:"peer_mac_address,omitempty"`
	PortDescription           string              `protobuf:"bytes,2,opt,name=port_description,json=portDescription,proto3" json:"port_description,omitempty"`
	SystemName                string              `protobuf:"bytes,3,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	SystemDescription         string              `protobuf:"bytes,4,opt,name=system_description,json=systemDescription,proto3" json:"system_description,omitempty"`
	TimeRemaining             uint32              `protobuf:"varint,5,opt,name=time_remaining,json=timeRemaining,proto3" json:"time_remaining,omitempty"`
	SystemCapabilities        string              `protobuf:"bytes,6,opt,name=system_capabilities,json=systemCapabilities,proto3" json:"system_capabilities,omitempty"`
	EnabledCapabilities       string              `protobuf:"bytes,7,opt,name=enabled_capabilities,json=enabledCapabilities,proto3" json:"enabled_capabilities,omitempty"`
	NetworkAddresses          *LldpAddrEntryEntry `protobuf:"bytes,8,opt,name=network_addresses,json=networkAddresses,proto3" json:"network_addresses,omitempty"`
	AutoNegotiation           string              `protobuf:"bytes,9,opt,name=auto_negotiation,json=autoNegotiation,proto3" json:"auto_negotiation,omitempty"`
	PhysicalMediaCapabilities string              `protobuf:"bytes,10,opt,name=physical_media_capabilities,json=physicalMediaCapabilities,proto3" json:"physical_media_capabilities,omitempty"`
	MediaAttachmentUnitType   uint32              `protobuf:"varint,11,opt,name=media_attachment_unit_type,json=mediaAttachmentUnitType,proto3" json:"media_attachment_unit_type,omitempty"`
	PortVlanId                uint32              `protobuf:"varint,12,opt,name=port_vlan_id,json=portVlanId,proto3" json:"port_vlan_id,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}            `json:"-"`
	XXX_unrecognized          []byte              `json:"-"`
	XXX_sizecache             int32               `json:"-"`
}

func (m *LldpNeighborDetail) Reset()         { *m = LldpNeighborDetail{} }
func (m *LldpNeighborDetail) String() string { return proto.CompactTextString(m) }
func (*LldpNeighborDetail) ProtoMessage()    {}
func (*LldpNeighborDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{4}
}
func (m *LldpNeighborDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpNeighborDetail.Unmarshal(m, b)
}
func (m *LldpNeighborDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpNeighborDetail.Marshal(b, m, deterministic)
}
func (dst *LldpNeighborDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpNeighborDetail.Merge(dst, src)
}
func (m *LldpNeighborDetail) XXX_Size() int {
	return xxx_messageInfo_LldpNeighborDetail.Size(m)
}
func (m *LldpNeighborDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpNeighborDetail.DiscardUnknown(m)
}

var xxx_messageInfo_LldpNeighborDetail proto.InternalMessageInfo

func (m *LldpNeighborDetail) GetPeerMacAddress() string {
	if m != nil {
		return m.PeerMacAddress
	}
	return ""
}

func (m *LldpNeighborDetail) GetPortDescription() string {
	if m != nil {
		return m.PortDescription
	}
	return ""
}

func (m *LldpNeighborDetail) GetSystemName() string {
	if m != nil {
		return m.SystemName
	}
	return ""
}

func (m *LldpNeighborDetail) GetSystemDescription() string {
	if m != nil {
		return m.SystemDescription
	}
	return ""
}

func (m *LldpNeighborDetail) GetTimeRemaining() uint32 {
	if m != nil {
		return m.TimeRemaining
	}
	return 0
}

func (m *LldpNeighborDetail) GetSystemCapabilities() string {
	if m != nil {
		return m.SystemCapabilities
	}
	return ""
}

func (m *LldpNeighborDetail) GetEnabledCapabilities() string {
	if m != nil {
		return m.EnabledCapabilities
	}
	return ""
}

func (m *LldpNeighborDetail) GetNetworkAddresses() *LldpAddrEntryEntry {
	if m != nil {
		return m.NetworkAddresses
	}
	return nil
}

func (m *LldpNeighborDetail) GetAutoNegotiation() string {
	if m != nil {
		return m.AutoNegotiation
	}
	return ""
}

func (m *LldpNeighborDetail) GetPhysicalMediaCapabilities() string {
	if m != nil {
		return m.PhysicalMediaCapabilities
	}
	return ""
}

func (m *LldpNeighborDetail) GetMediaAttachmentUnitType() uint32 {
	if m != nil {
		return m.MediaAttachmentUnitType
	}
	return 0
}

func (m *LldpNeighborDetail) GetPortVlanId() uint32 {
	if m != nil {
		return m.PortVlanId
	}
	return 0
}

type LldpUnknownTlvEntryItem struct {
	TlvType              uint32   `protobuf:"varint,1,opt,name=tlv_type,json=tlvType,proto3" json:"tlv_type,omitempty"`
	TlvValue             []byte   `protobuf:"bytes,2,opt,name=tlv_value,json=tlvValue,proto3" json:"tlv_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LldpUnknownTlvEntryItem) Reset()         { *m = LldpUnknownTlvEntryItem{} }
func (m *LldpUnknownTlvEntryItem) String() string { return proto.CompactTextString(m) }
func (*LldpUnknownTlvEntryItem) ProtoMessage()    {}
func (*LldpUnknownTlvEntryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{5}
}
func (m *LldpUnknownTlvEntryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpUnknownTlvEntryItem.Unmarshal(m, b)
}
func (m *LldpUnknownTlvEntryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpUnknownTlvEntryItem.Marshal(b, m, deterministic)
}
func (dst *LldpUnknownTlvEntryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpUnknownTlvEntryItem.Merge(dst, src)
}
func (m *LldpUnknownTlvEntryItem) XXX_Size() int {
	return xxx_messageInfo_LldpUnknownTlvEntryItem.Size(m)
}
func (m *LldpUnknownTlvEntryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpUnknownTlvEntryItem.DiscardUnknown(m)
}

var xxx_messageInfo_LldpUnknownTlvEntryItem proto.InternalMessageInfo

func (m *LldpUnknownTlvEntryItem) GetTlvType() uint32 {
	if m != nil {
		return m.TlvType
	}
	return 0
}

func (m *LldpUnknownTlvEntryItem) GetTlvValue() []byte {
	if m != nil {
		return m.TlvValue
	}
	return nil
}

type LldpUnknownTlvEntryEntry struct {
	LldpUnknownTlvEntry  []*LldpUnknownTlvEntryItem `protobuf:"bytes,1,rep,name=lldp_unknown_tlv_entry,json=lldpUnknownTlvEntry,proto3" json:"lldp_unknown_tlv_entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LldpUnknownTlvEntryEntry) Reset()         { *m = LldpUnknownTlvEntryEntry{} }
func (m *LldpUnknownTlvEntryEntry) String() string { return proto.CompactTextString(m) }
func (*LldpUnknownTlvEntryEntry) ProtoMessage()    {}
func (*LldpUnknownTlvEntryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{6}
}
func (m *LldpUnknownTlvEntryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpUnknownTlvEntryEntry.Unmarshal(m, b)
}
func (m *LldpUnknownTlvEntryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpUnknownTlvEntryEntry.Marshal(b, m, deterministic)
}
func (dst *LldpUnknownTlvEntryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpUnknownTlvEntryEntry.Merge(dst, src)
}
func (m *LldpUnknownTlvEntryEntry) XXX_Size() int {
	return xxx_messageInfo_LldpUnknownTlvEntryEntry.Size(m)
}
func (m *LldpUnknownTlvEntryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpUnknownTlvEntryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LldpUnknownTlvEntryEntry proto.InternalMessageInfo

func (m *LldpUnknownTlvEntryEntry) GetLldpUnknownTlvEntry() []*LldpUnknownTlvEntryItem {
	if m != nil {
		return m.LldpUnknownTlvEntry
	}
	return nil
}

type LldpOrgDefTlvEntryItem struct {
	Oui                  uint32   `protobuf:"varint,1,opt,name=oui,proto3" json:"oui,omitempty"`
	TlvSubtype           uint32   `protobuf:"varint,2,opt,name=tlv_subtype,json=tlvSubtype,proto3" json:"tlv_subtype,omitempty"`
	TlvInfoIndes         uint32   `protobuf:"varint,3,opt,name=tlv_info_indes,json=tlvInfoIndes,proto3" json:"tlv_info_indes,omitempty"`
	TlvValue             []byte   `protobuf:"bytes,4,opt,name=tlv_value,json=tlvValue,proto3" json:"tlv_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LldpOrgDefTlvEntryItem) Reset()         { *m = LldpOrgDefTlvEntryItem{} }
func (m *LldpOrgDefTlvEntryItem) String() string { return proto.CompactTextString(m) }
func (*LldpOrgDefTlvEntryItem) ProtoMessage()    {}
func (*LldpOrgDefTlvEntryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{7}
}
func (m *LldpOrgDefTlvEntryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpOrgDefTlvEntryItem.Unmarshal(m, b)
}
func (m *LldpOrgDefTlvEntryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpOrgDefTlvEntryItem.Marshal(b, m, deterministic)
}
func (dst *LldpOrgDefTlvEntryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpOrgDefTlvEntryItem.Merge(dst, src)
}
func (m *LldpOrgDefTlvEntryItem) XXX_Size() int {
	return xxx_messageInfo_LldpOrgDefTlvEntryItem.Size(m)
}
func (m *LldpOrgDefTlvEntryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpOrgDefTlvEntryItem.DiscardUnknown(m)
}

var xxx_messageInfo_LldpOrgDefTlvEntryItem proto.InternalMessageInfo

func (m *LldpOrgDefTlvEntryItem) GetOui() uint32 {
	if m != nil {
		return m.Oui
	}
	return 0
}

func (m *LldpOrgDefTlvEntryItem) GetTlvSubtype() uint32 {
	if m != nil {
		return m.TlvSubtype
	}
	return 0
}

func (m *LldpOrgDefTlvEntryItem) GetTlvInfoIndes() uint32 {
	if m != nil {
		return m.TlvInfoIndes
	}
	return 0
}

func (m *LldpOrgDefTlvEntryItem) GetTlvValue() []byte {
	if m != nil {
		return m.TlvValue
	}
	return nil
}

type LldpOrgDefTlvEntryEntry struct {
	LldpOrgDefTlvEntry   []*LldpOrgDefTlvEntryItem `protobuf:"bytes,1,rep,name=lldp_org_def_tlv_entry,json=lldpOrgDefTlvEntry,proto3" json:"lldp_org_def_tlv_entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LldpOrgDefTlvEntryEntry) Reset()         { *m = LldpOrgDefTlvEntryEntry{} }
func (m *LldpOrgDefTlvEntryEntry) String() string { return proto.CompactTextString(m) }
func (*LldpOrgDefTlvEntryEntry) ProtoMessage()    {}
func (*LldpOrgDefTlvEntryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{8}
}
func (m *LldpOrgDefTlvEntryEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpOrgDefTlvEntryEntry.Unmarshal(m, b)
}
func (m *LldpOrgDefTlvEntryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpOrgDefTlvEntryEntry.Marshal(b, m, deterministic)
}
func (dst *LldpOrgDefTlvEntryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpOrgDefTlvEntryEntry.Merge(dst, src)
}
func (m *LldpOrgDefTlvEntryEntry) XXX_Size() int {
	return xxx_messageInfo_LldpOrgDefTlvEntryEntry.Size(m)
}
func (m *LldpOrgDefTlvEntryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpOrgDefTlvEntryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LldpOrgDefTlvEntryEntry proto.InternalMessageInfo

func (m *LldpOrgDefTlvEntryEntry) GetLldpOrgDefTlvEntry() []*LldpOrgDefTlvEntryItem {
	if m != nil {
		return m.LldpOrgDefTlvEntry
	}
	return nil
}

type LldpNeighborMib struct {
	RemTimeMark          uint32                    `protobuf:"varint,1,opt,name=rem_time_mark,json=remTimeMark,proto3" json:"rem_time_mark,omitempty"`
	RemLocalPortNum      uint32                    `protobuf:"varint,2,opt,name=rem_local_port_num,json=remLocalPortNum,proto3" json:"rem_local_port_num,omitempty"`
	RemIndex             uint32                    `protobuf:"varint,3,opt,name=rem_index,json=remIndex,proto3" json:"rem_index,omitempty"`
	ChassisIdSubType     uint32                    `protobuf:"varint,4,opt,name=chassis_id_sub_type,json=chassisIdSubType,proto3" json:"chassis_id_sub_type,omitempty"`
	ChassisIdLen         uint32                    `protobuf:"varint,5,opt,name=chassis_id_len,json=chassisIdLen,proto3" json:"chassis_id_len,omitempty"`
	PortIdSubType        uint32                    `protobuf:"varint,6,opt,name=port_id_sub_type,json=portIdSubType,proto3" json:"port_id_sub_type,omitempty"`
	PortIdLen            uint32                    `protobuf:"varint,7,opt,name=port_id_len,json=portIdLen,proto3" json:"port_id_len,omitempty"`
	CombinedCapabilities uint32                    `protobuf:"varint,8,opt,name=combined_capabilities,json=combinedCapabilities,proto3" json:"combined_capabilities,omitempty"`
	UnknownTlvList       *LldpUnknownTlvEntryEntry `protobuf:"bytes,9,opt,name=unknown_tlv_list,json=unknownTlvList,proto3" json:"unknown_tlv_list,omitempty"`
	OrgDefTlvList        *LldpOrgDefTlvEntryEntry  `protobuf:"bytes,10,opt,name=org_def_tlv_list,json=orgDefTlvList,proto3" json:"org_def_tlv_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LldpNeighborMib) Reset()         { *m = LldpNeighborMib{} }
func (m *LldpNeighborMib) String() string { return proto.CompactTextString(m) }
func (*LldpNeighborMib) ProtoMessage()    {}
func (*LldpNeighborMib) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{9}
}
func (m *LldpNeighborMib) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpNeighborMib.Unmarshal(m, b)
}
func (m *LldpNeighborMib) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpNeighborMib.Marshal(b, m, deterministic)
}
func (dst *LldpNeighborMib) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpNeighborMib.Merge(dst, src)
}
func (m *LldpNeighborMib) XXX_Size() int {
	return xxx_messageInfo_LldpNeighborMib.Size(m)
}
func (m *LldpNeighborMib) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpNeighborMib.DiscardUnknown(m)
}

var xxx_messageInfo_LldpNeighborMib proto.InternalMessageInfo

func (m *LldpNeighborMib) GetRemTimeMark() uint32 {
	if m != nil {
		return m.RemTimeMark
	}
	return 0
}

func (m *LldpNeighborMib) GetRemLocalPortNum() uint32 {
	if m != nil {
		return m.RemLocalPortNum
	}
	return 0
}

func (m *LldpNeighborMib) GetRemIndex() uint32 {
	if m != nil {
		return m.RemIndex
	}
	return 0
}

func (m *LldpNeighborMib) GetChassisIdSubType() uint32 {
	if m != nil {
		return m.ChassisIdSubType
	}
	return 0
}

func (m *LldpNeighborMib) GetChassisIdLen() uint32 {
	if m != nil {
		return m.ChassisIdLen
	}
	return 0
}

func (m *LldpNeighborMib) GetPortIdSubType() uint32 {
	if m != nil {
		return m.PortIdSubType
	}
	return 0
}

func (m *LldpNeighborMib) GetPortIdLen() uint32 {
	if m != nil {
		return m.PortIdLen
	}
	return 0
}

func (m *LldpNeighborMib) GetCombinedCapabilities() uint32 {
	if m != nil {
		return m.CombinedCapabilities
	}
	return 0
}

func (m *LldpNeighborMib) GetUnknownTlvList() *LldpUnknownTlvEntryEntry {
	if m != nil {
		return m.UnknownTlvList
	}
	return nil
}

func (m *LldpNeighborMib) GetOrgDefTlvList() *LldpOrgDefTlvEntryEntry {
	if m != nil {
		return m.OrgDefTlvList
	}
	return nil
}

type LldpNeighborItem struct {
	ReceivingInterfaceName       string              `protobuf:"bytes,1,opt,name=receiving_interface_name,json=receivingInterfaceName,proto3" json:"receiving_interface_name,omitempty"`
	ReceivingParentInterfaceName string              `protobuf:"bytes,2,opt,name=receiving_parent_interface_name,json=receivingParentInterfaceName,proto3" json:"receiving_parent_interface_name,omitempty"`
	DeviceId                     string              `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ChassisId                    string              `protobuf:"bytes,4,opt,name=chassis_id,json=chassisId,proto3" json:"chassis_id,omitempty"`
	PortIdDetail                 string              `protobuf:"bytes,5,opt,name=port_id_detail,json=portIdDetail,proto3" json:"port_id_detail,omitempty"`
	HeaderVersion                uint32              `protobuf:"varint,6,opt,name=header_version,json=headerVersion,proto3" json:"header_version,omitempty"`
	HoldTime                     uint32              `protobuf:"varint,7,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	EnabledCapabilities          string              `protobuf:"bytes,8,opt,name=enabled_capabilities,json=enabledCapabilities,proto3" json:"enabled_capabilities,omitempty"`
	Platform                     string              `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`
	Detail                       *LldpNeighborDetail `protobuf:"bytes,10,opt,name=detail,proto3" json:"detail,omitempty"`
	Mib                          *LldpNeighborMib    `protobuf:"bytes,11,opt,name=mib,proto3" json:"mib,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}            `json:"-"`
	XXX_unrecognized             []byte              `json:"-"`
	XXX_sizecache                int32               `json:"-"`
}

func (m *LldpNeighborItem) Reset()         { *m = LldpNeighborItem{} }
func (m *LldpNeighborItem) String() string { return proto.CompactTextString(m) }
func (*LldpNeighborItem) ProtoMessage()    {}
func (*LldpNeighborItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{10}
}
func (m *LldpNeighborItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpNeighborItem.Unmarshal(m, b)
}
func (m *LldpNeighborItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpNeighborItem.Marshal(b, m, deterministic)
}
func (dst *LldpNeighborItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpNeighborItem.Merge(dst, src)
}
func (m *LldpNeighborItem) XXX_Size() int {
	return xxx_messageInfo_LldpNeighborItem.Size(m)
}
func (m *LldpNeighborItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpNeighborItem.DiscardUnknown(m)
}

var xxx_messageInfo_LldpNeighborItem proto.InternalMessageInfo

func (m *LldpNeighborItem) GetReceivingInterfaceName() string {
	if m != nil {
		return m.ReceivingInterfaceName
	}
	return ""
}

func (m *LldpNeighborItem) GetReceivingParentInterfaceName() string {
	if m != nil {
		return m.ReceivingParentInterfaceName
	}
	return ""
}

func (m *LldpNeighborItem) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *LldpNeighborItem) GetChassisId() string {
	if m != nil {
		return m.ChassisId
	}
	return ""
}

func (m *LldpNeighborItem) GetPortIdDetail() string {
	if m != nil {
		return m.PortIdDetail
	}
	return ""
}

func (m *LldpNeighborItem) GetHeaderVersion() uint32 {
	if m != nil {
		return m.HeaderVersion
	}
	return 0
}

func (m *LldpNeighborItem) GetHoldTime() uint32 {
	if m != nil {
		return m.HoldTime
	}
	return 0
}

func (m *LldpNeighborItem) GetEnabledCapabilities() string {
	if m != nil {
		return m.EnabledCapabilities
	}
	return ""
}

func (m *LldpNeighborItem) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LldpNeighborItem) GetDetail() *LldpNeighborDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *LldpNeighborItem) GetMib() *LldpNeighborMib {
	if m != nil {
		return m.Mib
	}
	return nil
}

type LldpNeighborEntry struct {
	LldpNeighbor         []*LldpNeighborItem `protobuf:"bytes,50,rep,name=lldp_neighbor,json=lldpNeighbor,proto3" json:"lldp_neighbor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LldpNeighborEntry) Reset()         { *m = LldpNeighborEntry{} }
func (m *LldpNeighborEntry) String() string { return proto.CompactTextString(m) }
func (*LldpNeighborEntry) ProtoMessage()    {}
func (*LldpNeighborEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_lldp_neighbor_20c02b2819426aa6, []int{11}
}
func (m *LldpNeighborEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpNeighborEntry.Unmarshal(m, b)
}
func (m *LldpNeighborEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpNeighborEntry.Marshal(b, m, deterministic)
}
func (dst *LldpNeighborEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpNeighborEntry.Merge(dst, src)
}
func (m *LldpNeighborEntry) XXX_Size() int {
	return xxx_messageInfo_LldpNeighborEntry.Size(m)
}
func (m *LldpNeighborEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpNeighborEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LldpNeighborEntry proto.InternalMessageInfo

func (m *LldpNeighborEntry) GetLldpNeighbor() []*LldpNeighborItem {
	if m != nil {
		return m.LldpNeighbor
	}
	return nil
}

func init() {
	proto.RegisterType((*LldpNeighborEntry_KEYS)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_neighbor_entry_KEYS")
	proto.RegisterType((*LldpL3Addr)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_l3_addr")
	proto.RegisterType((*LldpAddrEntryItem)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_addr_entry_item")
	proto.RegisterType((*LldpAddrEntryEntry)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_addr_entry_entry")
	proto.RegisterType((*LldpNeighborDetail)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_neighbor_detail")
	proto.RegisterType((*LldpUnknownTlvEntryItem)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_unknown_tlv_entry_item")
	proto.RegisterType((*LldpUnknownTlvEntryEntry)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_unknown_tlv_entry_entry")
	proto.RegisterType((*LldpOrgDefTlvEntryItem)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_org_def_tlv_entry_item")
	proto.RegisterType((*LldpOrgDefTlvEntryEntry)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_org_def_tlv_entry_entry")
	proto.RegisterType((*LldpNeighborMib)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_neighbor_mib")
	proto.RegisterType((*LldpNeighborItem)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_neighbor_item")
	proto.RegisterType((*LldpNeighborEntry)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.neighbors.details.detail.lldp_neighbor_entry")
}

func init() { proto.RegisterFile("lldp_neighbor.proto", fileDescriptor_lldp_neighbor_20c02b2819426aa6) }

var fileDescriptor_lldp_neighbor_20c02b2819426aa6 = []byte{
	// 1197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcf, 0x8b, 0x1c, 0x45,
	0x14, 0xa6, 0xdd, 0xcd, 0xee, 0xcc, 0x9b, 0x1f, 0x99, 0xd4, 0x26, 0x71, 0x92, 0x8d, 0x26, 0x0e,
	0x06, 0x23, 0x92, 0x11, 0x37, 0x12, 0x04, 0x41, 0x08, 0x26, 0xe0, 0x60, 0xb2, 0x86, 0xde, 0x1f,
	0x20, 0x8a, 0x45, 0x4d, 0x77, 0xcd, 0x4c, 0xb1, 0x5d, 0xd5, 0x4d, 0x75, 0x4d, 0xef, 0x2e, 0x9e,
	0xbc, 0x78, 0x12, 0x14, 0x3c, 0xc5, 0x8b, 0xfe, 0x1d, 0x0a, 0xfe, 0x4f, 0x1e, 0xbd, 0xc9, 0xab,
	0xaa, 0xee, 0x9d, 0x9e, 0xec, 0x82, 0x87, 0x9d, 0x4b, 0xcf, 0xf4, 0x57, 0x5f, 0xbd, 0x57, 0xef,
	0xab, 0xf7, 0x5e, 0x55, 0xc3, 0x56, 0x92, 0xc4, 0x19, 0x55, 0x5c, 0x4c, 0x67, 0xe3, 0x54, 0x0f,
	0x33, 0x9d, 0x9a, 0x94, 0x7c, 0x11, 0x89, 0x3c, 0x4a, 0xa9, 0x48, 0x73, 0x7a, 0xa2, 0x29, 0x37,
	0x33, 0xae, 0x15, 0x37, 0xd4, 0x52, 0xd3, 0x8c, 0xeb, 0x21, 0xfe, 0x1b, 0xaa, 0x34, 0xe6, 0xb9,
	0x7d, 0x0e, 0xcb, 0xf9, 0xf9, 0x30, 0xe6, 0x86, 0x89, 0xa4, 0xfc, 0x1d, 0x7c, 0x0f, 0xfd, 0x9a,
	0x03, 0xca, 0x95, 0xd1, 0xa7, 0xf4, 0xcb, 0x67, 0x5f, 0xef, 0x91, 0x6d, 0x68, 0xe2, 0x64, 0xaa,
	0x98, 0xe4, 0xfd, 0xe0, 0x5e, 0xf0, 0xa0, 0x19, 0x36, 0x10, 0xd8, 0x65, 0x92, 0x93, 0xfb, 0xd0,
	0x15, 0xca, 0x70, 0x3d, 0x61, 0x91, 0x67, 0xbc, 0x61, 0x19, 0x9d, 0x0a, 0xb5, 0xb4, 0x6d, 0x68,
	0xc6, 0xbc, 0x10, 0x11, 0xa7, 0x22, 0xee, 0xaf, 0x39, 0x1b, 0x0e, 0x18, 0xc5, 0x83, 0x63, 0x68,
	0x5b, 0xe7, 0xc9, 0x23, 0xca, 0xe2, 0x58, 0x93, 0x77, 0xa0, 0x8d, 0xbf, 0x3c, 0xcf, 0xa9, 0x39,
	0xcd, 0x4a, 0x9f, 0x2d, 0x8f, 0xed, 0x9f, 0x66, 0x1c, 0x29, 0x22, 0x2b, 0x3e, 0xa6, 0x1e, 0xf3,
	0x4e, 0x5b, 0x88, 0x3d, 0x71, 0x90, 0xa7, 0x3c, 0xae, 0x28, 0x6b, 0x15, 0xe5, 0xb1, 0xa7, 0x0c,
	0xfe, 0x0e, 0xe0, 0xba, 0xf5, 0x8c, 0x1c, 0x1f, 0xb2, 0x30, 0x5c, 0x92, 0x0c, 0x36, 0xcb, 0x69,
	0xe8, 0xbc, 0xb5, 0x73, 0x38, 0xbc, 0x2c, 0xa9, 0x87, 0x8b, 0xa1, 0x86, 0xa5, 0x1b, 0xf2, 0x16,
	0x80, 0x64, 0x34, 0x9f, 0x8f, 0x6d, 0xc4, 0x18, 0x4e, 0x27, 0x6c, 0x4a, 0xb6, 0xe7, 0x00, 0x72,
	0x03, 0x36, 0xc4, 0x84, 0xaa, 0xb9, 0xb4, 0x61, 0x74, 0xc2, 0x2b, 0x62, 0xb2, 0x3b, 0x97, 0x83,
	0x3f, 0x02, 0xb8, 0xb1, 0x1c, 0x80, 0x7d, 0x92, 0x1f, 0x03, 0xb8, 0xba, 0x34, 0xd2, 0x0f, 0xee,
	0xad, 0x3d, 0x68, 0xed, 0x7c, 0x77, 0xc9, 0xa1, 0x2c, 0x69, 0x17, 0x76, 0x10, 0x45, 0x85, 0x9f,
	0x21, 0x36, 0xf8, 0xfd, 0x8a, 0xd7, 0xb8, 0x4a, 0x2d, 0x37, 0x99, 0x3c, 0x80, 0x5e, 0xc6, 0xb9,
	0xa6, 0x92, 0x45, 0x74, 0x51, 0xec, 0x66, 0xd8, 0x45, 0xfc, 0x05, 0x8b, 0xca, 0x9d, 0x7c, 0x1f,
	0x7a, 0x59, 0xaa, 0x0d, 0x8d, 0x79, 0x1e, 0x69, 0x91, 0x19, 0x91, 0x2a, 0xbf, 0xe1, 0x57, 0x11,
	0x7f, 0x7a, 0x06, 0x93, 0xbb, 0xd0, 0xca, 0x4f, 0x73, 0xc3, 0xa5, 0xcb, 0x45, 0xb7, 0xe7, 0xe0,
	0x20, 0x9b, 0x88, 0x0f, 0x81, 0x78, 0xc2, 0xa2, 0xb5, 0x75, 0xcb, 0xbb, 0xe6, 0x46, 0x16, 0xed,
	0xdd, 0x87, 0xae, 0x11, 0x92, 0x53, 0xcd, 0x25, 0x13, 0x4a, 0xa8, 0x69, 0xff, 0x8a, 0xd5, 0xbf,
	0x83, 0x68, 0x58, 0x82, 0xe4, 0x43, 0xd8, 0xf2, 0x56, 0x23, 0x96, 0xb1, 0xb1, 0x48, 0x84, 0x11,
	0x3c, 0xef, 0x6f, 0x58, 0xb3, 0xde, 0xe1, 0xe7, 0x0b, 0x23, 0xe4, 0x23, 0xb8, 0xce, 0x15, 0x1b,
	0x27, 0x3c, 0xae, 0xcf, 0xd8, 0xb4, 0x33, 0xb6, 0xfc, 0x58, 0x6d, 0xca, 0x4f, 0x01, 0x5c, 0x53,
	0xdc, 0x1c, 0xa7, 0xfa, 0xa8, 0xd4, 0x8b, 0xe7, 0xfd, 0x86, 0x4d, 0x4f, 0xba, 0xba, 0x3d, 0xb5,
	0xcf, 0xb0, 0xe7, 0x3d, 0x3f, 0x29, 0x1d, 0xe3, 0xa6, 0xb0, 0xb9, 0x49, 0xa9, 0xe2, 0xd3, 0xd4,
	0x08, 0x66, 0x65, 0x6c, 0xba, 0x4d, 0x41, 0x7c, 0xf7, 0x0c, 0x26, 0x9f, 0xc1, 0x76, 0x36, 0x3b,
	0xcd, 0x45, 0xc4, 0x12, 0x2a, 0x79, 0x2c, 0x58, 0x3d, 0x66, 0xb0, 0xb3, 0x6e, 0x95, 0x94, 0x17,
	0xc8, 0xa8, 0x45, 0xfe, 0x29, 0xdc, 0x76, 0xd3, 0x98, 0x31, 0x2c, 0x9a, 0x49, 0xae, 0x0c, 0x9d,
	0x2b, 0x61, 0x5c, 0x77, 0x68, 0xd9, 0x0d, 0x79, 0xd3, 0x32, 0x9e, 0x54, 0x84, 0x03, 0x25, 0x8c,
	0xed, 0x14, 0xf7, 0xa0, 0x6d, 0x93, 0xa7, 0x48, 0x98, 0xc2, 0xe6, 0xd3, 0xb6, 0x74, 0x40, 0xec,
	0x30, 0x61, 0x6a, 0x14, 0x0f, 0x0e, 0x60, 0xdb, 0x06, 0x3d, 0x57, 0x47, 0x2a, 0x3d, 0x56, 0xd4,
	0x24, 0xc5, 0x62, 0x2f, 0xb8, 0x05, 0x0d, 0x44, 0xaa, 0x4e, 0xd4, 0x09, 0x37, 0x4d, 0x52, 0x58,
	0xdb, 0xdb, 0xd0, 0xc4, 0xa1, 0x82, 0x25, 0x73, 0x57, 0xb3, 0xed, 0x10, 0xb9, 0x87, 0xf8, 0x3e,
	0xf8, 0x2b, 0x80, 0x3b, 0x17, 0xd8, 0x75, 0x25, 0xfa, 0x5b, 0x00, 0x37, 0xcf, 0x27, 0xf8, 0x4a,
	0xe5, 0x97, 0xbc, 0xab, 0xe7, 0x07, 0x18, 0xda, 0xa3, 0xe5, 0xc0, 0x8d, 0xed, 0x27, 0x85, 0x2b,
	0xdb, 0x5f, 0x03, 0xaf, 0x4a, 0xaa, 0xa7, 0x34, 0xe6, 0x93, 0x65, 0x55, 0x7a, 0xb0, 0x96, 0xce,
	0x85, 0x17, 0x04, 0xff, 0x62, 0xe9, 0x21, 0xa7, 0xde, 0xc2, 0xc0, 0x24, 0x45, 0xd9, 0xc3, 0xde,
	0x85, 0x2e, 0x12, 0x84, 0x9a, 0xa4, 0x54, 0xa8, 0x98, 0xe7, 0xbe, 0x97, 0xb5, 0x4d, 0x52, 0x8c,
	0xd4, 0x24, 0x1d, 0x21, 0x56, 0xd7, 0x74, 0x7d, 0x49, 0xd3, 0x3f, 0x4b, 0x4d, 0x5f, 0x5f, 0x95,
	0xd3, 0xf4, 0x55, 0xa9, 0xe9, 0x6b, 0x84, 0x15, 0x69, 0x7a, 0xbe, 0x3c, 0x21, 0xc1, 0xc1, 0xaf,
	0xf4, 0xf4, 0x29, 0x9f, 0x54, 0x92, 0xfe, 0xbb, 0x0e, 0xd7, 0xea, 0x9d, 0x50, 0x8a, 0x31, 0x19,
	0x40, 0x47, 0x73, 0x49, 0x6d, 0x97, 0x91, 0x4c, 0x1f, 0x79, 0x49, 0x5b, 0x9a, 0xcb, 0x7d, 0x21,
	0xf9, 0x0b, 0xa6, 0x8f, 0xc8, 0x07, 0x40, 0x90, 0x93, 0xa4, 0x58, 0x41, 0x36, 0x9b, 0xf1, 0x24,
	0x70, 0x0a, 0x5f, 0xd5, 0x5c, 0x3e, 0xc7, 0x81, 0x97, 0xa9, 0x36, 0xbb, 0x73, 0x89, 0x02, 0x22,
	0x19, 0x15, 0x3e, 0xf1, 0x0a, 0x37, 0x34, 0x97, 0xa8, 0xee, 0x09, 0x79, 0x08, 0x5b, 0xd1, 0x8c,
	0xe5, 0xb9, 0xc8, 0xa9, 0x88, 0x71, 0xaf, 0x5c, 0x5e, 0xaf, 0x5b, 0x5a, 0xcf, 0x0f, 0x8d, 0xe2,
	0xbd, 0xf9, 0x78, 0xdf, 0x6f, 0xd9, 0x02, 0x3d, 0xe1, 0xca, 0xb7, 0xbf, 0x76, 0xc5, 0x7c, 0xce,
	0x15, 0x79, 0xcf, 0xf7, 0xe7, 0x45, 0x8b, 0x1b, 0xae, 0x4d, 0x22, 0x7e, 0x66, 0xee, 0x6d, 0x68,
	0x95, 0x44, 0xb4, 0xb5, 0xe9, 0x4e, 0x39, 0xc7, 0x41, 0x43, 0x8f, 0xe0, 0x46, 0x94, 0xca, 0xb1,
	0x50, 0xcb, 0x6d, 0xb1, 0x61, 0x99, 0xd7, 0xcb, 0xc1, 0x5a, 0x77, 0xf8, 0x25, 0x80, 0xde, 0x62,
	0x66, 0x27, 0x22, 0x37, 0xb6, 0x13, 0xb5, 0x76, 0x26, 0x2b, 0x2f, 0x20, 0xd7, 0x1d, 0xbb, 0xf3,
	0xaa, 0x7a, 0x9e, 0x8b, 0xdc, 0x90, 0x9f, 0x03, 0xe8, 0x2d, 0x26, 0x86, 0x5d, 0x12, 0xac, 0x64,
	0x49, 0x17, 0x14, 0x42, 0xd8, 0x49, 0xcb, 0xe4, 0xc3, 0x15, 0x0d, 0xfe, 0x59, 0x07, 0x52, 0xcf,
	0x3d, 0x5b, 0xc5, 0x9f, 0x40, 0x5f, 0xf3, 0x88, 0x8b, 0x42, 0xa8, 0x29, 0x5d, 0xba, 0xc7, 0xb9,
	0xb3, 0xf8, 0x66, 0x35, 0x3e, 0xaa, 0x5d, 0xe8, 0x9e, 0xc1, 0xdd, 0xb3, 0x99, 0x19, 0xd3, 0xd8,
	0x93, 0xcf, 0xbd, 0x08, 0xde, 0xa9, 0x68, 0x2f, 0x2d, 0x6b, 0xf4, 0xbf, 0xef, 0x85, 0x78, 0x27,
	0x3a, 0xcb, 0x3e, 0x7f, 0x46, 0x37, 0xab, 0xcc, 0xc3, 0xe4, 0x2c, 0xb3, 0xc9, 0x29, 0x62, 0x93,
	0xb3, 0x19, 0xb6, 0x5d, 0x42, 0x3d, 0x75, 0xd7, 0x8c, 0xfb, 0xd0, 0x9d, 0x71, 0x16, 0x73, 0x4d,
	0x0b, 0xae, 0x73, 0x3c, 0xa5, 0x7c, 0x6a, 0x3a, 0xf4, 0xd0, 0x81, 0xb8, 0x90, 0x59, 0x9a, 0xc4,
	0xb6, 0x0e, 0x7d, 0x62, 0x36, 0x10, 0xc0, 0x1a, 0xbc, 0xf0, 0xb4, 0x6e, 0x5c, 0x7c, 0x5a, 0xdf,
	0x86, 0x46, 0x96, 0x30, 0x33, 0x49, 0xb5, 0xf4, 0xc7, 0x62, 0xf5, 0x4e, 0x0a, 0xd8, 0xf0, 0x0b,
	0x76, 0x39, 0x71, 0xd9, 0x37, 0xb2, 0xa5, 0x9b, 0x56, 0xe8, 0xbd, 0x11, 0x09, 0x6b, 0x52, 0x8c,
	0xed, 0x81, 0xd9, 0xda, 0xf9, 0x66, 0x55, 0x4e, 0xa5, 0x18, 0x87, 0xe8, 0x67, 0xf0, 0x2a, 0x58,
	0xfa, 0x6a, 0xf1, 0x3d, 0xfa, 0x87, 0x00, 0x3a, 0x35, 0xbc, 0xbf, 0x63, 0x5b, 0xf3, 0xb7, 0xab,
	0x5a, 0x91, 0xed, 0xc8, 0xf6, 0x13, 0x63, 0xd7, 0x43, 0xe3, 0x0d, 0xfb, 0x01, 0xf5, 0xe8, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x95, 0x35, 0x22, 0x57, 0x0d, 0x00, 0x00,
}
